### ISSUE TITLE
Pourquoi le C et C++ ?

### ISSUE THREAD

**Issue by baptiste-pellarin** [Atma21/Music_Transfert#1]
Pourquoi ce faire du mal ?

**Comment by baptiste-pellarin** [comment]
Tu as des problèmes dans ta vie ?

**Comment by Ooggle** [comment]
Très bonnes performances, langage compilé, nativement multiplateforme, pas besoin de modules supplémentaires ni d'abstraction, véritable maîtrise du code, de la compilation et du linker.
En résumé c'est bien.
Je pense qu'on peut clore l'issue.
